version: "3.7"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.9.7-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    networks:
    - sonar
    volumes:
      - type: bind
        source: ./sonarqube/data
        target: /opt/sonarqube/data
      - type: bind
        source: ./sonarqube/extensions
        target: /opt/sonarqube/extensions
      - type: bind
        source: ./sonarqube/logs
        target: /opt/sonarqube/logs
  init:
      image: bash
      privileged: true
      user: root
      volumes:
        - ./init.sh:/mnt/init.sh 
      command: ["sh", "-e", "/mnt/init.sh"]
  db:
    image: postgres:12
    networks:
      - sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - type: bind
        source: ./postgresql/conf
        target: /var/lib/postgresql
      - type: bind
        source: ./postgresql/data
        target: /var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
    - sonar
    ports:
      - 443:443
    volumes:
    - ./ssl/:/etc/ssl
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:z
networks:
  sonar:
    driver: bridge